/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coagent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author axelknutsson
 */
public class ClientsJPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form ClientsJPanel
     */
    public ClientsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHomeCli = new javax.swing.JPanel();
        btnShowClient = new javax.swing.JButton();
        btnEditClient = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panelShowCli = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShowCli = new javax.swing.JTable();
        txtShowSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnShowBack = new javax.swing.JButton();
        panelEditCli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditCli = new javax.swing.JTable();
        btnAddCli = new javax.swing.JButton();
        btnUpdateCli = new javax.swing.JButton();
        btnDeleteCli = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtEditSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelHomeCli.setMinimumSize(new java.awt.Dimension(250, 250));

        btnShowClient.setText("Show Clients");
        btnShowClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowClientActionPerformed(evt);
            }
        });

        btnEditClient.setText("Edit Clients");
        btnEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClientActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Clients options");

        javax.swing.GroupLayout panelHomeCliLayout = new javax.swing.GroupLayout(panelHomeCli);
        panelHomeCli.setLayout(panelHomeCliLayout);
        panelHomeCliLayout.setHorizontalGroup(
            panelHomeCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeCliLayout.createSequentialGroup()
                .addGroup(panelHomeCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeCliLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panelHomeCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowClient, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(btnEditClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelHomeCliLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel6)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panelHomeCliLayout.setVerticalGroup(
            panelHomeCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeCliLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(btnShowClient, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        add(panelHomeCli, "card2");

        panelShowCli.setMinimumSize(new java.awt.Dimension(250, 250));

        tblShowCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact", "Email"
            }
        ));
        jScrollPane2.setViewportView(tblShowCli);

        txtShowSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtShowSearchKeyReleased(evt);
            }
        });

        jLabel5.setText("Search:");

        btnShowBack.setText("Back");
        btnShowBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShowCliLayout = new javax.swing.GroupLayout(panelShowCli);
        panelShowCli.setLayout(panelShowCliLayout);
        panelShowCliLayout.setHorizontalGroup(
            panelShowCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShowCliLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(panelShowCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShowBack)
                    .addGroup(panelShowCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelShowCliLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtShowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        panelShowCliLayout.setVerticalGroup(
            panelShowCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowCliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShowCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowBack)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(panelShowCli, "card4");

        panelEditCli.setMinimumSize(new java.awt.Dimension(250, 250));

        jLabel1.setText("Name:");

        jLabel2.setText("Contact:");

        jLabel3.setText("Email:");

        tblEditCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact", "Email"
            }
        ));
        tblEditCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEditCli);

        btnAddCli.setText("Add");
        btnAddCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCliActionPerformed(evt);
            }
        });

        btnUpdateCli.setText("Update");
        btnUpdateCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCliActionPerformed(evt);
            }
        });

        btnDeleteCli.setText("Delete");
        btnDeleteCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCliActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtEditSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditSearchKeyReleased(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.setMaximumSize(new java.awt.Dimension(91, 52));
        jButton1.setMinimumSize(new java.awt.Dimension(91, 52));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Search:");

        javax.swing.GroupLayout panelEditCliLayout = new javax.swing.GroupLayout(panelEditCli);
        panelEditCli.setLayout(panelEditCliLayout);
        panelEditCliLayout.setHorizontalGroup(
            panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditCliLayout.createSequentialGroup()
                        .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelEditCliLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEditCliLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContact))
                            .addGroup(panelEditCliLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditCliLayout.createSequentialGroup()
                        .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEditCliLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEditSearch))
                            .addGroup(panelEditCliLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        panelEditCliLayout.setVerticalGroup(
            panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditCliLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCli))
                .addGap(18, 18, 18)
                .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditCliLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditCliLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(14, 14, 14))))
        );

        add(panelEditCli, "card5");
    }// </editor-fold>//GEN-END:initComponents

// gör bara show panelen synlig och fyller i table med clients.
    private void btnShowClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowClientActionPerformed
        panelHomeCli.setVisible(false);
        panelShowCli.setVisible(true);
        panelEditCli.setVisible(false);
        show_client(tblShowCli);
    }//GEN-LAST:event_btnShowClientActionPerformed
// gör bara edit panelen synlig fyller i table med clients
    private void btnEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClientActionPerformed
        panelHomeCli.setVisible(false);
        panelShowCli.setVisible(false);
        panelEditCli.setVisible(true);
        show_client(tblEditCli);
    }//GEN-LAST:event_btnEditClientActionPerformed
    
    // gör bara "hemskärmen" synlig.
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // button back
        panelHomeCli.setVisible(true);
        panelShowCli.setVisible(false);
        panelEditCli.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    // uppdaterar table i edit
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // button refresh
        show_client(tblEditCli);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // tar bort en vald client i en table. 
    private void btnDeleteCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCliActionPerformed
        deleteClient(tblEditCli);
    }//GEN-LAST:event_btnDeleteCliActionPerformed

        // lägger till en client som står i textfälten.
    private void btnAddCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCliActionPerformed
        addClient();
    }//GEN-LAST:event_btnAddCliActionPerformed
    
    // gör bara "hemskärmen" syndlig.
    private void btnShowBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBackActionPerformed
        panelHomeCli.setVisible(true);
        panelShowCli.setVisible(false);
        panelEditCli.setVisible(false);
    }//GEN-LAST:event_btnShowBackActionPerformed
    
    // kan söka på namn, nr och email. (problem: är känsligt för stor/ liten bokstav)
    private void txtShowSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtShowSearchKeyReleased
        DefaultTableModel table = (DefaultTableModel) tblShowCli.getModel();
        String search = txtShowSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tblShowCli.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtShowSearchKeyReleased
    
    // kan söka på namn, nr och email. (problem: är känsligt för stor/ liten bokstav)
    private void txtEditSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditSearchKeyReleased
        DefaultTableModel table = (DefaultTableModel) tblEditCli.getModel();
        String search = txtEditSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tblEditCli.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtEditSearchKeyReleased

    // Om man klickar på en rad i table i edit så fylls textrutorna i. 
    private void tblEditCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditCliMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel) tblEditCli.getModel();
        
        String tblName = tblModel.getValueAt(tblEditCli.getSelectedRow(), 0).toString();
        String tblContact = tblModel.getValueAt(tblEditCli.getSelectedRow(), 1).toString();
        String tblEmail = tblModel.getValueAt(tblEditCli.getSelectedRow(), 2).toString();
        
        // lägg till text i textrutorna
        txtName.setText(tblName);
        txtContact.setText(tblContact);
        txtEmail.setText(tblEmail);
    }//GEN-LAST:event_tblEditCliMouseClicked
    
    // uppdaterar en client till det som står i textfälten.
    private void btnUpdateCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCliActionPerformed
        updateClient();    
    }//GEN-LAST:event_btnUpdateCliActionPerformed

    // skapar en arraylist som sparar clients namn, contact och emails.  
    public ArrayList<ClientsJPanel.Client> clientList(){
        ArrayList<ClientsJPanel.Client> userList = new ArrayList<>();
        try{
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/coagent?serverTimezone=UTC";
            String username = "root";
            String password = "";
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("SELECT Clients_Name, Clients_Contact, Clients_Email FROM clients");
            ClientsJPanel.Client user;
            while (rs.next()){ 
                user = new ClientsJPanel.Client(rs.getString("clients_Name"), rs.getString("clients_Contact"), rs.getString("clients_Email"));
                userList.add(user);
            }
        } catch (Exception e){JOptionPane.showMessageDialog(null, e);}
        return userList;
    }
    
    
    /* visar clients, skriver ut arraylisten ovanför till en table.
        Har flera tables så har input table, så man vet till vilket table
        som arraylisten ska skrivas ut till.
    */
    public void show_client(JTable table){
        
        ArrayList<ClientsJPanel.Client> list = clientList();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];
        for (int i = 0; i<list.size(); i++){
            row[0]= list.get(i).getclients_Name();
            row[1]= list.get(i).getclients_Contact();
            row[2]= list.get(i).getclients_Email();
            model.addRow(row);   
        }
       
    }
    
    // Lägger till clients till databasen.
    public void addClient(){
        String name = txtName.getText();
        String contact = txtContact.getText();
        String email = txtEmail.getText();
        
        try{
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/coagent?serverTimezone=UTC";
            String username = "root";
            String password = "";
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();
            String sql = "INSERT INTO clients(Clients_Name, Clients_Contact, Clients_Email) VALUES('"+name+"', '"+contact+"', '"+email+"')";
            stm.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Client is added");
            

        } catch (Exception e){System.out.println("e");}
    }
    
    // tar bort clients till databasen.
    public void deleteClient(JTable table){
        try{
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/coagent?serverTimezone=UTC";
            String username = "root";
            String password = "";
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            
            
            int row = table.getSelectedRow();
            String name = table.getValueAt(row, 0).toString();
            String sql = "DELETE FROM clients WHERE Clients_Name = ?";
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, name);
            stm.executeUpdate();
            stm.close();
            JOptionPane.showMessageDialog(null, "Delete succesfully");
            
        } catch (Exception e){System.out.println("e");}  
    }
    
    //ändrar clients i databasen. 
    public void updateClient(){
        String name = txtName.getText();
        String contact = txtContact.getText();
        String email = txtEmail.getText();
        try {
            
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/coagent?serverTimezone=UTC";
            String username = "root";
            String password = "";
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();
            
            int row = tblEditCli.getSelectedRow();
            String value = tblEditCli.getModel().getValueAt(row, 0).toString();
            String sql = "UPDATE clients SET Clients_Name = '"+name+"', Clients_Contact = '"+contact+"', Clients_Email = '"+email+"' WHERE Clients_Name = '"+value+"'";
            
            stm.executeUpdate(sql);
            

            JOptionPane.showMessageDialog(null, "Update succesfully");

            
        }catch (Exception e){System.out.println("e");} 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCli;
    private javax.swing.JButton btnDeleteCli;
    private javax.swing.JButton btnEditClient;
    private javax.swing.JButton btnShowBack;
    private javax.swing.JButton btnShowClient;
    private javax.swing.JButton btnUpdateCli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelEditCli;
    private javax.swing.JPanel panelHomeCli;
    private javax.swing.JPanel panelShowCli;
    private javax.swing.JTable tblEditCli;
    private javax.swing.JTable tblShowCli;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEditSearch;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtShowSearch;
    // End of variables declaration//GEN-END:variables
private static class Client {
        private String clients_Name, clients_Contact, clients_Email;
        public Client(String clients_Name, String clients_Contact, String clients_Email) {
            
            this.clients_Name = clients_Name;
            this.clients_Contact = clients_Contact;
            this.clients_Email = clients_Email;
        }
        public String getclients_Name(){
            return clients_Name;
        }
        public String getclients_Contact(){
            return clients_Contact;
        }
        public String getclients_Email(){
            return clients_Email;
        }
    }

}
