/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coagent;

import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author lenovo
 */
public class SubmissionsPanel extends javax.swing.JPanel {

    String[] dbTables = {
            "books",
            "editors",
            "publishers",
        };
        String[] dbColumns = {
            "Books_title",
            "Editor_Name",
            "Publisher_Name",
        };
       
        String[] dbIds = {
            "Books_Id",
            "Editor_Id",
            "Publisher_Id",
        };
    
    
    /**
     * Creates new form Submissions
     */
    public SubmissionsPanel() {
        initComponents();
        
        ((DefaultTableCellRenderer)tableSearchSub.getDefaultRenderer(Object.class)).setBackground(new Color(190,227,219));
        tableSearchSub.setGridColor(new Color(190,227,219));
        jScrollPane2.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JPanel();
        lblBookTitle = new javax.swing.JLabel();
        lblEditorName = new javax.swing.JLabel();
        lblReplyGrade = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBookTitle = new javax.swing.JComboBox<>();
        comboReplyReceived = new javax.swing.JComboBox<>();
        comboEditor = new javax.swing.JComboBox<>();
        comboDate = new javax.swing.JComboBox<>();
        comboReplyGrade = new javax.swing.JComboBox<>();
        lblPublisher = new javax.swing.JLabel();
        comboPublisher = new javax.swing.JComboBox<>();
        lblSubmissionHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfieldSubSearch = new javax.swing.JTextPane();
        btbSearch = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSearchSub = new javax.swing.JTable();
        btnNewSub = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(190, 227, 219));
        setToolTipText("");
        setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        lblDate.setBackground(new java.awt.Color(250, 249, 249));

        lblBookTitle.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        lblBookTitle.setText("Book");

        lblEditorName.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        lblEditorName.setText("Editor");

        lblReplyGrade.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        lblReplyGrade.setText("Reply");

        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel5.setText("Reply received ");

        jLabel6.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel6.setText("Date");

        comboBookTitle.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        comboBookTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboReplyReceived.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        comboReplyReceived.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboEditor.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        comboEditor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboDate.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        comboDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboReplyGrade.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        comboReplyGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPublisher.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        lblPublisher.setText("Publisher");

        comboPublisher.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        comboPublisher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout lblDateLayout = new javax.swing.GroupLayout(lblDate);
        lblDate.setLayout(lblDateLayout);
        lblDateLayout.setHorizontalGroup(
            lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDateLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblDateLayout.createSequentialGroup()
                        .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(lblDateLayout.createSequentialGroup()
                                .addComponent(lblBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lblDateLayout.createSequentialGroup()
                                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPublisher))
                                .addGap(18, 18, 18)
                                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPublisher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboReplyReceived, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEditorName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboEditor, 0, 222, Short.MAX_VALUE)
                                    .addComponent(comboDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(lblDateLayout.createSequentialGroup()
                        .addComponent(lblReplyGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboReplyGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        lblDateLayout.setVerticalGroup(
            lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDateLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookTitle)
                    .addComponent(comboBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditorName)
                    .addComponent(lblPublisher)
                    .addComponent(comboPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboReplyReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReplyGrade)
                    .addComponent(comboReplyGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        lblSubmissionHeader.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        lblSubmissionHeader.setText("Submissions");

        txtfieldSubSearch.setBackground(new java.awt.Color(249, 250, 250));
        txtfieldSubSearch.setBorder(null);
        txtfieldSubSearch.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        txtfieldSubSearch.setOpaque(false);
        jScrollPane1.setViewportView(txtfieldSubSearch);

        btbSearch.setBackground(new java.awt.Color(250, 249, 249));
        btbSearch.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        btbSearch.setText("Search submissions");
        btbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSearchActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jButton3.setText("Save changes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(190, 227, 219));
        jScrollPane2.setForeground(new java.awt.Color(190, 227, 219));
        jScrollPane2.setToolTipText("");

        tableSearchSub.setBackground(new java.awt.Color(190, 227, 219));
        tableSearchSub.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        tableSearchSub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Book", "Editor", "Publisher"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSearchSub.setCellSelectionEnabled(true);
        tableSearchSub.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tableSearchSub.setGridColor(new java.awt.Color(250, 249, 249));
        tableSearchSub.setInheritsPopupMenu(true);
        tableSearchSub.setSelectionForeground(new java.awt.Color(250, 249, 249));
        jScrollPane2.setViewportView(tableSearchSub);
        tableSearchSub.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnNewSub.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        btnNewSub.setText("Create new submission");

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 10)); // NOI18N
        jLabel2.setText("Search in submissions by a book's title or an editor's name.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSubmissionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNewSub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(btbSearch))))
                .addGap(64, 107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSubmissionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnNewSub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbSearch;
    private javax.swing.JButton btnNewSub;
    private javax.swing.JComboBox<String> comboBookTitle;
    private javax.swing.JComboBox<String> comboDate;
    private javax.swing.JComboBox<String> comboEditor;
    private javax.swing.JComboBox<String> comboPublisher;
    private javax.swing.JComboBox<String> comboReplyGrade;
    private javax.swing.JComboBox<String> comboReplyReceived;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBookTitle;
    private javax.swing.JPanel lblDate;
    private javax.swing.JLabel lblEditorName;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblReplyGrade;
    private javax.swing.JLabel lblSubmissionHeader;
    private javax.swing.JTable tableSearchSub;
    private javax.swing.JTextPane txtfieldSubSearch;
    // End of variables declaration//GEN-END:variables
}
